### ISSUE TITLE
Update Chinese translation on home page

### ISSUE THREAD

**Issue by dissentertainer** [Official-MoonDao/moondaowww#31]
The lines below need to be translated:

[Line 143](https://github.com/Official-MoonDao/moondaowww/commit/d837756f32826cd2d26bad838d16547d398c1146#diff-26ca35c3be6d07c84bb77f1e63a1b19487279d5b9c9a9392179b3a35647e1254R143)
[Line 149](https://github.com/Official-MoonDao/moondaowww/commit/d837756f32826cd2d26bad838d16547d398c1146#diff-26ca35c3be6d07c84bb77f1e63a1b19487279d5b9c9a9392179b3a35647e1254R149)
[Line 165](https://github.com/Official-MoonDao/moondaowww/commit/d837756f32826cd2d26bad838d16547d398c1146#diff-26ca35c3be6d07c84bb77f1e63a1b19487279d5b9c9a9392179b3a35647e1254R165)

Also, it looks like the "What's next?" button is currently pointing to a localhost href instead of '/docs/launch-path#-moon-phase-2-send-a-moondao-member-to-space-in-2022'

**Comment by larrotiz** [comment]
What's next button link is now fixed

**Comment by dissentertainer** [comment]
Cool, thanks @larrotiz
