### ISSUE TITLE
Translations Procedure

### ISSUE THREAD

**Issue by irquintanas** [Official-MoonDao/moondaowww#41]
Hi, I would like to translate the web into Spanish, but I am not sure how. I expected there were some files with equivalences between English and some other languages, but it seems not to work this way...

Can anybody clear the process up?

Thanks

**Comment by 0xb00** [comment]
Hi @irquintanas! 

The instruction for generating the message files and performing translations are here: https://github.com/Official-MoonDao/moondaowww#internationalization. You should be able use `es` for the locale code. Take a look at that and let me know if you run into any troubles.

Gracias!

**Comment by irquintanas** [comment]
OK @0xb00, thanks, let me try and I'll come to you if not able.

**Comment by irquintanas** [comment]
Hi @0xb00, I have made the translation but now I need permissions in the rep in order to create a branch and send the Pull Request.

**Comment by dissentertainer** [comment]
Hi @irquintanas, I've added you as a repository collaborator. Go ahead and create your branch and submit your PR for review.

**Comment by irquintanas** [comment]
Thank you, submittted

**Comment by irquintanas** [comment]
Hi, @0xb00, @dissentertainer, I would like to translate as well the Documentation section. How would the procedure be? Translatig the .md files in the Documentation folder?

**Comment by dissentertainer** [comment]
@irquintanas My understanding of the Docusaurus documentation for the docs plugin is that we will need to create a directory called "current" for the `es` locale, and then add `.md` or `.mdx` files that match the files in our main `docs` directory. For example:

```
moondaowww/i18n/es/docusaurus-plugin-content-docs/
│
│ # translations for moondaowww/docs
|├── current
│   ├── contribute.md
│   ├── faq.md
│   ├── introduction.md
│   ├── launch_path.md
│   ├── team.md
│   └── token.md
├── current.json
│
```

Of course, every time an edit is made to our docs we will need to update the translations files, but it's manageable as long as we are in good communication.

**Comment by irquintanas** [comment]
OK, I understand. Let's try that way. Thanks

**Comment by irquintanas** [comment]
> @irquintanas My understanding of the Docusaurus documentation for the docs plugin is that we will need to create a directory called "current" for the `es` locale, and then add `.md` or `.mdx` files that match the files in our main `docs` directory. For example:
> 
> ```
> moondaowww/i18n/es/docusaurus-plugin-content-docs/
> │
> │ # translations for moondaowww/docs
> |├── current
> │   ├── contribute.md
> │   ├── faq.md
> │   ├── introduction.md
> │   ├── launch_path.md
> │   ├── team.md
> │   └── token.md
> ├── current.json
> │
> ```
> 
> Of course, every time an edit is made to our docs we will need to update the translations files, but it's manageable as long as we are in good communication.

Hi @dissentertainer, yes your proposal works fine locally! So give me please a few days to translate the files and I will propose a new PR.

Thanks!
