### ISSUE TITLE
CN and ES translation crossing

### ISSUE THREAD

**Issue by irquintanas** [Official-MoonDao/moondaowww#48]
When selecting the CN option in tha languages, the Spanish version appears, while the Documentation is shown in English. @dissentertainer, @0xb00 can you check? Something I can do?

**Comment by dissentertainer** [comment]
@irquintanas I'm not able to replicate this on my end (macOS Chrome). What browser and OS are you using? I did notice that Google Translate launches a popup and attempts to automatically translate the page. Could it be possible that it is set to auto translate to Spanish in your Google Translate settings? See the attached screenshot.
![Screen Shot 2022-02-13 at 12 32 15 PM](https://user-images.githubusercontent.com/6757420/153767116-807cba92-d7a0-4c04-a192-b14da86c8527.png)

@larrotiz Can you take a look on your machine as well?

**Comment by irquintanas** [comment]
So sorry, you are completely right @dissentertainer
