### ISSUE TITLE
Update Chinese translation for main heading and buy button

### ISSUE THREAD

**Issue by dissentertainer** [Official-MoonDao/moondaowww#53]
@yzStrive @goofystoic We made a couple of edits to the front page of the website that will need to be updated in Chinese.

1. Changed "Send a MoonDAO member to space!" to "We are sending MoonDAO members to space!"
https://github.com/Official-MoonDao/moondaowww/blob/main/i18n/zh-Hans/code.json#L288

2. Changed "What's next?" to "Buy $MOONEY"
https://github.com/Official-MoonDao/moondaowww/blob/main/i18n/zh-Hans/code.json#L348

**Comment by yzStrive** [comment]
ok, I can do this.

**Comment by yzStrive** [comment]
@dissentertainer  https://github.com/Official-MoonDao/moondaowww/pull/58 . pls for code review

**Comment by dissentertainer** [comment]
Closed by #58

**Comment by 0xRabbit0** [comment]
cool
